Fix trascriber error handling and support mp4 conversion
M4R774/bobweb2 pull request #243
Opened 2023-05-09 04:50 UTC by Latemus

- Fixed TranscribeCommand error handling so that it now informs if there was an error. Problem: TranscribingError did not call super in init and as such raised error itself when it was caught
- Fixed TranscribeCommand media conversion so that it supports mp4 files. Problem: Conversion from mp4 to mp3 exported the audio in some codec that the OpenaiAPI did not support. Now all audio is converted to mp4 without video (m4a) and then sent to OpenaiAPI

2023-05-10 16:32 UTC, taturl commented on bobweb/bob/message_handler_voice.py
> +        response = f'Median tekstittäminen ei onnistunut. {e.reason or ""}'
Yleisesti olisi varmaan parempi että virheviestin syy menisi vain lokiin. Tai jos syyn haluaa näyttää käyttäjille, niin määrittelisi jokaisen tapauksen tähän valmiiksi.

2023-05-10 16:37 UTC, taturl requested changes
Jos lisää vielä tarvittavat testit niin approved.

2023-05-14 11:29 UTC, Latemus commented
@taturl Testikattavuus lisätty. Valmis uudelleenarviointia varten. Samalla poistettu ffmpeg riippuvuus paikallisesta ajamisesta ja lisätty tiedot reamde.md, että se on riippuvuus jonka tarvitsee vain muutamaan komennon paikalliseen ajamiseen

2023-05-14 11:31 UTC, Latemus commented
@taturl Laitettu automerge päälle, joten jos korjattavaa niin suoraan vain requires changes

2023-05-14 13:11 UTC, taturl commented on bobweb/bob/test_audio_transcribing.py
> +        # As the buffer size is over 1 byte over 25 MB, should return error that states the file is too big
```suggestion
```

2023-05-14 13:12 UTC, taturl commented on bobweb/bob/test_audio_transcribing.py
> +        # As the buffer size is over 1 byte over 25 MB, should return error that states the file is too big
The over 25 MB  error test case is below this one, right?

2023-05-14 13:19 UTC, taturl commented on README_PyCharm_Ultimate.md
> +# PyCharm Ultimate version asetusten valmistelu
Tämmöisen voisi ehkä laittaa vain tuohon yleiseen README-tiedostoon yhdeksi otsikoksi. Toki jos halutaan mennä siihen että eri README-tiedostoja niin OK, mutta kokemuksen mukaan kukaan ei löydä muita tiedostoja kuin pää-readme:n (eivätkä lue edes siitä kuin ekat rivit).

2023-05-14 13:24 UTC, taturl commented on README.md
> +- **Muita ei paikollisia**
```suggestion
- **Muita ei-pakollisia**
```

2023-05-14 13:28 UTC, taturl commented on bobweb/bob/main.py
> +def notify_if_ffmpeg_not_available():
Pitäisikö tälle vielä kirjoittaa testi? Tilanne jossa `ffmpeg --version` palauttaa true ja tilanne jos se feilaa. Sillä devaaja näkisi heti että kyseessä on tähän ffmpeg:hen liittyvä tilanne.

2023-05-14 13:30 UTC, taturl requested changes
Muutama kommentti vielä, voi suorittaa jos haluaa.

2023-05-14 14:25 UTC, Latemus commented on README_PyCharm_Ultimate.md
> +# PyCharm Ultimate version asetusten valmistelu
Joo. Nappasin pois siitä perus README:sta kun järkeilin, että suurimmalle osalle turhaa tietoa, kun ei juurikaan enää kehittäjillä opiskelijalisenssejä, joilla saisi ton Ultimaten, mutten kuitenkaan halunnut poistaa tietoa koko projektista. Mutta palautin nyt README:n pohjalle ja viittauksen tuonne vaatimus-listaukseen.

2023-05-14 15:06 UTC, Latemus commented on bobweb/bob/main.py
> +def notify_if_ffmpeg_not_available():
Nyt siis noi testit ei oo enää riippuvaisia ffmpeg:stä. Pistetty sinne readme:hin optional-vaatimuksena, koska tarvii pelkästään tähän tekstitä-komentoon, eikä sen takia mielekästä pakottaa kaikkia asentamaan. Nappaan pois sen myös tuolta gitlab-runnerin ympäristöstä, niin ei hämää siellä.

2023-05-14 15:07 UTC, Latemus commented on bobweb/bob/main.py
> +def notify_if_ffmpeg_not_available():
Enkä siis halunnut, että testiajo failaa turhaan jos ffmpeg ei oo asennettuna juuri koska ylimääräinen riippuvuus jota tarvitaan vain pieneen osaan.

2023-05-14 15:11 UTC, Latemus commented
Nappasin nyt automergen kuitenkin pois, jos tulee jotain pientä korjattavaa kuten kirjotusvirhettä tms, niin voi antaa approvalin ja korjattavan kohdan tms.

2023-05-14 16:44 UTC, taturl approved these changes

2023-05-14 17:37 UTC, merged