Add quick systems message option to gpt command
M4R774/bobweb2 pull request #244
Opened 2023-05-14 16:43 UTC by taturl

Sometimes you want to use different system messages quickly. With this PR we add an option to use one of ready-made system prompts (1, 2 or 3) when using gpt.

E.g.

```
/gpt /2 Can I have an answer in Finnish?
```

Prompts without quick message use the old per-channel saved system message as previously.

If this is good, we could add next options to customize the "save slots" for the three quick system prompts.

2023-05-15 18:35 UTC, Latemus requested changes
Testit pitäis saada paremmiksi ja kopioitu sisältö pois tosta ohjetekstistä (vanhenisi heti ensimmäisen muutoksen jälkeen, kun unohtuisi päivittää ohjeteksti)

2023-05-15 18:35 UTC, Latemus commented on bobweb/bob/command_gpt.py
> +        }
Tää dict staattiseks (luokan ulkopuolelle), kun ei syytä miksi luokan jäsenenä

2023-05-15 18:35 UTC, Latemus commented on bobweb/bob/test_command_gpt.py
> +        self.assertEqual(expected_reply, chat.last_bot_txt())
Nää 2 ekaa on sama, mutta eri parametrilla? Lisäks toi toinen yliajaa nyt ensimmäisen kun näillä sama nimi. Näissä ei nyt varmistu, että sinne OpenAI:lle lähtis se annettua parametria vastaava system message. Jos haluais varmistaa sen lähtevän system messagen, niin vois esim:

```python
    def test_quick_system_prompt(self):
        openai_api_utils.state.reset_cost_so_far()
        mock_method = MagicMock()
        mock_method.return_value = MockOpenAIObject()
        with mock.patch('openai.ChatCompletion.create', mock_method):
            chat, _, user = init_chat_with_bot_cc_holder_and_another_user()
            user.send_message('/gpt /1 Who won the world series in 2020?')

            expected_system_msg = gpt_command.quick_system_prompts.get('1')
            expected_call_args = [{'role': 'system', 'content': expected_system_msg},
                                  {'role': 'user', 'content': 'Who won the world series in 2020?'}]
            mock_method.assert_called_with(model='gpt-4', messages=expected_call_args)
```

2023-05-15 20:54 UTC, taturl reviewed
Korjattu kommenttien perusteella.

2023-05-15 20:54 UTC, taturl commented on bobweb/bob/command_gpt.py
> +        }
Siirretty staattiseksi

2023-05-15 20:54 UTC, taturl commented on bobweb/bob/command_gpt.py
> +    " 3: You are an expert code developer with teaching skills."
Laitettu pika-system viestit ohjeessa tulemaan dictistä. Lisätty uudet rivit per numero

2023-05-15 20:54 UTC, taturl commented on bobweb/bob/test_command_gpt.py
Lisätty importtiin. Nyt yksittäisen testin ajo onnistuu.

2023-05-15 20:54 UTC, taturl commented on bobweb/bob/test_command_gpt.py
> +        self.assertEqual(expected_reply, chat.last_bot_txt())
Uudelleenkirjoitettu testit esimerkin avulla.

2023-05-15 20:54 UTC, taturl commented on bobweb/bob/test_command_gpt.py
> +        self.assertEqual(expected_reply, chat.last_bot_txt())
Nyt testi kokeilee että lähtevä konteksti on oikea tapauksessa jossa yritetään ei-olemassaolevaa pika system messagea

2023-05-16 16:48 UTC, Latemus approved these changes
Tää on ok

2023-05-16 16:48 UTC, Latemus commented on bobweb/bob/command_gpt.py
> +"""
Tää ok. Tässä vois toki vielä laittaa ton koko listan tuleen automaattisesti tuolta quick_system_prompts dictistä, esim:

```suggestion
quick_system_prompts_str = ''.join([f'\n{key}: {value}' for key, value in quick_system_prompts.items()])

no_parameters_given_notification_msg = f"""
    Anna jokin syöte komennon
    jälkeen. [.!/]gpt (syöte). Voit valita jonkin kolmesta
    valmiista ohjeistusviestistä laittamalla numeron 1-3
    ennen syötettä.
    {quick_system_prompts_str}
"""
```
Tossa toki tollanen ei niin selkeä list interpolalaatio. Ei tarvi tässä muuttaa, tarjoan vain näkökulmaa.

2023-05-16 16:57 UTC, taturl commented on bobweb/bob/command_gpt.py
> +"""
Katsotaan tuota sitten seuraavassa iteraatiossa.

2023-05-16 16:58 UTC, merged