Add quick system prompts as a json field to db
M4R774/bobweb2 pull request #246
Opened 2023-05-16 18:30 UTC by taturl

With this PR you can get and set quick system prompts from database.

```
/gpt /1 = This sets this message as test prompt to "1" quick system prompt slot
````

2023-05-19 16:52 UTC, Latemus requested changes
Hyvää settiä. Osa kommenteista ehdotuksia ja osa suoria muutoskehoituksia. Uudelta logiikalta puuttu vielä testit kokonaan.

2023-05-19 16:52 UTC, Latemus commented on bobweb/bob/command_gpt.py
> +    """
Tästä multiline String aiheuttaa tekstin preformatoitumisen niin, että se sisältää noi rivinvaihdot ja rivin sisennykset. Voisi korjata:

```suggestion
    no_parameters_given_notification_msg = \
        f'Anna jokin syöte komennon jälkeen. [.!/]gpt (syöte). Voit valita jonkin kolmesta valmiista ' \
        f'ohjeistusviestistä laittamalla numeron 1-3 ennen syötettä. {quick_system_prompts_str}'
```

2023-05-19 16:52 UTC, Latemus commented on bobweb/bob/command_gpt.py
> +            update.effective_message.reply_text(f"Uusi pikaohjausviesti {sub_command} on nyt:\n\n{current_prompt}")
Molemmille lohkoille yhteiset koodit vain kertaalleen ennen lohkoja.
```
            quick_system_prompts = database.get_quick_system_prompts(update.effective_message.chat_id)
            current_prompt = quick_system_prompts[sub_command]
```

2023-05-19 16:52 UTC, Latemus commented on bobweb/bob/command_gpt.py
> +            current_prompt = quick_system_prompts[sub_command]
migraatiossa ei ole default-arvoa tolle kentälle, joten tuo `get_quick_system_prompts` palauttaa `None`, jos chattiin ei ole vielä asetettu arvoa, jolloin seuraava rivi aiheuttaa poikkeuksen

2023-05-19 16:52 UTC, Latemus commented on bobweb/bob/database.py
> +    quick_system_prompts[new_quick_prompt_key] = new_quick_prompt_value
Tästä nousee poikkeus, jos chattiin ei ole vielä asetettu tota quick_system_prompts arvoa

2023-05-19 16:52 UTC, Latemus commented on bobweb/web/bobapp/migrations/0027_chat_quick_system_prompts.py
> +    ]
JSONField hyvä valinta, vaikuttaa näppärältä ja juuri sopivalta tälläiseen! Nyt kun noita tallennetaan tietokantaan, niin huomiona, että tällä hetkellä noiden quickSystemPromptien avaimet on tekstityyppisiä numeroiden sijaan. Lähinnä pieni nyanssi, jolla voi olla jotain vaikutuksia myöhemmin. Sillain hauska, että tällä toteutuksella voisi asettaa esim emojin tollasen promptin avaimeks (jos regex matcher myöhemmin muuttuu sen sallivaksi).

2023-05-19 17:18 UTC, taturl commented on bobweb/bob/command_gpt.py
> +            update.effective_message.reply_text(f"Uusi pikaohjausviesti {sub_command} on nyt:\n\n{current_prompt}")
Done

2023-05-19 17:54 UTC, taturl commented on bobweb/bob/command_gpt.py
> +            current_prompt = quick_system_prompts[sub_command]
Asetettu default-arvoksi tyhjä dict.

2023-05-19 17:54 UTC, taturl commented on bobweb/bob/database.py
> +    quick_system_prompts[new_quick_prompt_key] = new_quick_prompt_value
Lisätty default-arvo quick_system_promptsille

2023-05-19 18:09 UTC, taturl commented on bobweb/web/bobapp/migrations/0027_chat_quick_system_prompts.py
> +    ]
Juu, laitoin tarkoituksella noin. Jos halutaan käyttää vaikka kirjaimia tai muita tunnisteita numeroiden sijaan.

2023-05-24 17:38 UTC, Latemus approved these changes
Hyvä, testitkin nyt lisätty. Voi mergettää sisään. Pieni huomio, jonka voi vielä tehdä ennen sitä:
- Migraatiot voisi kaikki tiivistää yhteen, etei tämä haara lisää niitä 4 kappaletta, joista 1 on kokonaan tyhjä (?). Tiivistämisestä oli jokin pätkä readme.md, mutta lyhyesti poistat ne migraatio-tiedostot ja ajat komennot `migrate bobapp X`, missä X tätä haaraa edeltänyt migraatio ja sen jälkeen uudelleen `makemigrations`. niin kaikki tän haaran muutokset tiivistyy yhteen. Jos korjaat tän, niin ei tarvi uudelleenarviointia.

2023-05-24 17:38 UTC, Latemus commented on bobweb/bob/command_gpt.py
> +            update.effective_message.reply_text(f"Uusi pikaohjausviesti {sub_command} asetettu.")
Tämä hyvä! Ei turhaan toista komennon viestin sisältöä.

2023-05-24 19:36 UTC, merged